### ISSUE TITLE
Fix ConcatVCF

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/CAW#398]
```
N E X T F L O W  ~  version 0.22.2 4076
CANCER ANALYSIS WORKFLOW ~ 1.1 - d22920490f
Workflow execution stopped with the following message: null

N E X T F L O W  ~  version 0.22.2 4076
CANCER ANALYSIS WORKFLOW ~ 1.1 - d22920490f
Command Line: nextflow run [...]main.nf -c [...]/nextflow.config --project [...] --genome GRCh38 --step skipPreprocessing --
tools HaplotypeCaller,VEP,snpEff --sample Preprocessing/Recalibrated/recalibrated.tsv
Project Dir : [...]/CAW/default
Launch Dir  : [...]
Work Dir    : /scratch
TSV file    : [...]/Preprocessing/Recalibrated/recalibrated.tsv
Genome      : GRCh38
Step        : skippreprocessing
Tools       : haplotypecaller, vep, snpeff
Completed at: Thu Jul 27 08:13:27 CEST 2017
Duration    : 19h 48m 57s
Success     : false
Exit status : 141
Error report: Error executing process > 'ConcatVCF (gvcf-hc-[...])'Caused by:
 Process ConcatVCF (gvcf-hc-[...]) terminated with an error exit status (141)
```

**Comment by marcelm** [comment]
No idea what is going on, but exit code 141 is SIGPIPE.

**Comment by yafeng** [comment]
[alena_sample_caw.analysis.log](https://github.com/SciLifeLab/CAW/files/1413783/alena_sample_caw.analysis.log)

Hi, I also got the same problem when running the CAW workflow on a in-house server. Don't have a clue how to fix it. Can you help me?

**Comment by marcelm** [comment]
@yafeng Thanks,

**Comment by yafeng** [comment]
Hi,i tried several times with `-resume` option, it always failed at ConcatVCF command. 
Have you figured out what causing this error?

**Comment by marcelm** [comment]
We have not figured it out, yet, but we have updated the pipeline to automatically re-run the ConcatVCF step if it fails. However, if it *always* fails, then that will of course not work.

When you re-run the pipeline, do you always get the line that says `Exit status : 141`?

**Comment by szilvajuhos** [comment]
@yafeng looks you still have 1.2.1, and we have fixed quite a few things since that version. The current is 1.2.4, and even 1.2.3 works pretty well for me.

**Comment by yafeng** [comment]
Yes, when I rerun with this version, I always get `error Exit status: 141`.
Should I rerun like this with latest version? `nextflow run -latest SciLifeLab/CAW --sample mysample.tsv -resume`

**Comment by MaxUlysse** [comment]
Are you running on `milou`?

**Comment by yafeng** [comment]
No,  I am running on a local linux server in our lab.

**Comment by MaxUlysse** [comment]
Oh, yes, I remember.
Do you have internet access on this server?

**Comment by yafeng** [comment]
YES, I have internet access.

**Comment by MaxUlysse** [comment]
OK, so if I remember well, on `1.1` we did not switched to Singularity yet.
So you will need to install Singularity 2.3 and to update Nextflow to at least 0.25.0.

**Comment by yafeng** [comment]
I have Singularity 2.4 and nextflow version 0.25.7.4531 installed.

**Comment by MaxUlysse** [comment]
OK, so I think you're almost set.
I see that you were specifying a `nextflow.config` file, was it one you made for your server?
Which executor are you using?

**Comment by yafeng** [comment]
Yes, I specified a `genomes.config` so that it can find locally hg38 genome bundle files, which were downloaded  from `Milou` (/sw/data/uppnex/ToolBox/hg38bundle)

**Comment by MaxUlysse** [comment]
I think you just need to specify the ENV variable `NXF_SINGULARITY_CACHEDIR` to where the singularity containers will be downloaded.
`export NXF_SINGULARITY_CACHEDIR=/path/to/directory`
And if you can add the `containers.config` and `singularity.config` file in your config file, that should be working without further modification.

**Comment by yafeng** [comment]
btw, I was actually running with caw 1.2.1.  
Do you mean the error 141 will likely be solved when I set all the configs files as you said?

**Comment by MaxUlysse** [comment]
So you already had everything set up for Singularity in fact.
Sorry, I misread the version number earlier.
So you might not need to do anything on the config files in the end...
Sorry about that...
I'm hoping this new version will fix your problem, otherwise, we will see ;-) :crossed_fingers:

**Comment by yafeng** [comment]
I have rerun multiple times with `-latest` option (caw 1.2.4). 
It still failed at the same step with 
`Exit status : 141
  Error report: Error executing process > ConcatVCF 
`

**Comment by szilvajuhos** [comment]
Could you please forward the .nextflow.log file as well? There is a small test you can try in the scripts directory, `scripts/test.sh` that should be all right as well, could you please check this, and send us the error if there is any `scripts/test.sh 2>&1 | tee test.log `?

**Comment by yafeng** [comment]
I tried this two commands, both worked well.
`nextflow run -latest SciLifeLab/CAW/buildReferences.nf --download --genome smallGRCh37 -profile singularity `

`nextflow run -latest SciLifeLab/CAW --test --genome smallGRCh37 --noReports -profile singularity`

[test.log.txt](https://github.com/SciLifeLab/CAW/files/1431574/test.log.txt)

**Comment by marcelm** [comment]
I would like to know where exactly in the ConcatVCF script the failure occurs.

Can you please do the following: Run the pipeline, wait for the error message, then change to the work directory that is mentioned at the end of that error message. In the case of the `...test2.log` file, for example, you got this output at the end:
```
Work dir:
  /Z/yafzh/CAW_analysis/Alena_data/work/66/6498fc201043178ebe684c42f303d6
```
(If that directory still exists, you can of course also use that one.)

I’d appreciate if you could let us know
- whether there are any `.vcf` files in the working directory (these are the input files)
- whether a file named `header` exists in that directory and if so, whether it looks like a complete VCF header (that is, the last line should be `#CHROM  POS ID  REF ALT QUAL ...`.
- whether any `.vcf.gz` files exist. There should be only one. If that exists, I would like to know how complete it is. You can run `zcat thefile.vcf.gz | tail` to see the last few lines in the file. Do you see no output, just the VCF header or real VCF records? If the latter, which chromosome name do you see? If it is a chromosome in the middle of GRCh38, this would indicate that the file was written only partially.

**Comment by yafeng** [comment]
Here are the answers:

1. whether there are any .vcf files in the working directory (these are the input files)
    **there are many vcf files in the folder**
2. whether a file named header exists in that directory and if so, whether it looks like a complete VCF header.
   **the file `header` is not in the folder.**
3. whether any .vcf.gz files exist.
 **there isn't any .vcf.gz file in the folder.**

**Comment by MaxUlysse** [comment]
Can you show us the `.command.error` file?

**Comment by yafeng** [comment]
where is it? I didn't see the `.command.error` file in the folder.

**Comment by MaxUlysse** [comment]
sorry, it's `.command.err`

**Comment by MaxUlysse** [comment]
And it should be in the same folder where @marcelm was asking you to look for vcf files, and header...

**Comment by MaxUlysse** [comment]
it's a hidden file, so maybe a `ls -la` would help finding it

**Comment by yafeng** [comment]
OK, it was hidden.  the `.command.err` file is empty. There are other .command files, which one would you like to see. 
`
-rw-rw-r--  1 yafzh yafzh     0 okt 31 17:23 .command.begin

-rw-rw-r--  1 yafzh yafzh    97 okt 31 17:23 .command.env

-rw-rw-r--  1 yafzh yafzh     0 okt 31 17:23 .command.err

-rw-rw-r--  1 yafzh yafzh     0 okt 31 17:23 .command.log

-rw-rw-r--  1 yafzh yafzh     0 okt 31 17:23 .command.out

-rw-rw-r--  1 yafzh yafzh 34665 okt 31 17:23 .command.run

-rw-rw-r--  1 yafzh yafzh  2667 okt 31 17:23 .command.run.1

-rw-rw-r--  1 yafzh yafzh  1631 okt 31 17:23 .command.sh

-rw-rw-r--  1 yafzh yafzh     3 okt 31 17:23 .command.trace

-rw-rw-r--  1 yafzh yafzh     3 okt 31 17:23 .exitcode
`

**Comment by MaxUlysse** [comment]
ok...
So if both the `.command.err` and the `.command.log` are empty it means that we probably, nothing was executed at all...
Can you execute the `.command.run` just to verify, and give me the output.
```
bash .command.run
```

**Comment by yafeng** [comment]
the command is terminated, here is the output,
`/Z/yafzh/CAW_analysis/Alena_data/work/66/6498fc201043178ebe684c42f303d6/.command.run.1: line 99:  9392 Terminated              nxf_trace "$pid" .command.trace`

**Comment by MaxUlysse** [comment]
can you show me the `.command.sh` file

**Comment by yafeng** [comment]
[command.sh.txt](https://github.com/SciLifeLab/CAW/files/1433757/command.sh.txt)
here it is

**Comment by MaxUlysse** [comment]
Ok, so one more thing, can you try execute the .command.sh from within the singularity container?
Something like that should do it:
```
singularity exec /pathToContainers/caw-1.2.3.img bash .command.sh
```

**Comment by yafeng** [comment]
didn't find a similar `.img` file you mentioned. 

am I looking at the correct folder?
`ls /Z/yafzh/.nextflow/assets/SciLifeLab/CAW/containers/`
caw/            freebayes/      igvtools/       mutect1/        qualimap/       runallelecount/ snpeffgrch37/   vepgrch37/      
fastqc/         gatk/           multiqc/        picard/         r-base/         snpeff/         snpeffgrch38/   vepgrch38/

**Comment by MaxUlysse** [comment]
It's probably in the `NXF_SINGULARITY_CACHEDIR` that I asked you to set up yesterday.

**Comment by yafeng** [comment]
I didn't remember if I have set this one or where I have set it. Is there anything I can try to find it out, 
I tried `echo $NXF_SINGULARITY_CACHEDIR` , nothing shows up

**Comment by MaxUlysse** [comment]
is there a `singularity` directory in the `work` directory ?
the containers can be there too.

**Comment by yafeng** [comment]
Yes, there is one
`ls ~/CAW_analysis/Alena_data/work/singularity/`
maxulysse-caw-1.2.1.img            maxulysse-fastqc-1.2.1.img         .maxulysse-multiqc-1.2.1.img.lock  maxulysse-picard-1.2.1.img         maxulysse-qualimap-1.2.3.img       
maxulysse-caw-1.2.3.img            maxulysse-gatk-1.2.1.img           maxulysse-mutect1-1.2.1.img        maxulysse-qualimap-1.2.1.img

**Comment by MaxUlysse** [comment]
Perfect, then from the `/Z/yafzh/CAW_analysis/Alena_data/work/66/6498fc201043178ebe684c42f303d6/` directory you should be able to launch
```
singularity exec ~/CAW_analysis/Alena_data/work/singularity/maxulysse-caw-1.2.3.img bash .command.sh
```

**Comment by yafeng** [comment]
OK, this command works! no error.
some new files have been generated.
`header`
`mutect1_3998_tumor_vs_1913_normal.vcf.gz`
`mutect1_3998_tumor_vs_1913_normal.vcf.gz.tbi`

**Comment by MaxUlysse** [comment]
OK, so finally a good news...
It means that there is no problem with that particular process...
Can you resume your last command with the `--verbose` option, so that I have more output, and know what process really succeed, and fine which one is causing all that...

**Comment by yafeng** [comment]
You mean like this?
`singularity exec ~/CAW_analysis/Alena_data/work/singularity/maxulysse-caw-1.2.3.img bash .command.sh --verbose`

I tried, no error and no additional information

**Comment by MaxUlysse** [comment]
Oh, no, sorry, I meant like:
```
nextflow run -latest SciLifeLab/CAW --sample alena_sample.tsv --step mapping --tools mutect1,mutect2,strelka --genome GRCh38 -c /Z/yafzh/bin/CAW/configuration/genomes.config --totalMemory 60G -profile singularity -resume --verbose
```

**Comment by yafeng** [comment]
OK, i tried and it is still running. 
the last part of the log file is
`Submitted process > RunBcftoolsStats (mutect1_3998_tumor_vs_1913_normal.vcf.gz)`

Maybe the process is able to continue now somehow with the new files generated.

**Comment by MaxUlysse** [comment]
Maybe, but if that's the case, I still don't understand what was the problem in the first place...
One part of me is hoping for no more failure, so that we fixed the problem, and that would be perfect...

But another part of me is hoping for a failure, so so I can have more clues about what happened here.

Just let me know the outcome of all this.
:crossed_fingers:

**Comment by yafeng** [comment]
Yes,I agree it would be good to figure out what the problem is, so that It won't happen again.
I will let you know when the process is finished and post the log file here. 
Thanks for all your help so far!

**Comment by yafeng** [comment]
[alena_sample_caw.analysis.2017.11.01.log](https://github.com/SciLifeLab/CAW/files/1437621/alena_sample_caw.analysis.2017.11.01.log)

[trace.txt](https://github.com/SciLifeLab/CAW/files/1437622/trace.txt)

Hi, here are the reports. Actually, I can't see from log file if it is a successful run or not.

**Comment by MaxUlysse** [comment]
Hej,
As far as I'm concerned, it seems like it's still running.
So good news.

But I looked a little more in this more detailed log.
And it seems that you have 3 T/N pairs in this instance of CAW.

Are these 3 pairs from 3 different patients?
If yes, they should have different `ID`, in your case, they all share the same `ID`: SUBJECT_ID.

So for the Variant Calling CAW is trying to match every Tumor with every normal, and you end up with 9 pairs.

CAW can handle samples from different patients, if they are labeled in the TSV files as such.
To avoid such problem we advise to run an instance of CAW for every T/N pair.

Will you need some help regarding that?

**Comment by MaxUlysse** [comment]
CAW process the normal and tumor files and pull them together, so all your files were processed the same way, so I would definitively recommend to rerun everything.

Your new TSV file should work fine, but I would recommend to run 3 different instances of CAW just to be safe, it'll be easier to look at your results in the end if all the files are not in the same folders ;-)
If you do that I'll advice to set up this `NXF_SINGULARITY_CACHEDIR` otherwise you might download the container several times.

**Comment by yafeng** [comment]
I see, thanks for the tips!

**Comment by MaxUlysse** [comment]
OK, so I think this issue can finally be closed ;-).
If you have any more problem, don't hesitate to send me an email or to make another issue ;-).

**Comment by yafeng** [comment]
Hi, I have tried run 3 different instances of CAW as you suggested. 
All failed at the same command ConcatVCF. I checked the folder VariantCalling,  it seems strelka vcf outputs can always be successfully concatenated, mutect results are not. 

[sample_1913_caw.analysis.log](https://github.com/SciLifeLab/CAW/files/1446287/sample_1913_caw.analysis.log)
[sample_3713_caw.analysis.log](https://github.com/SciLifeLab/CAW/files/1446288/sample_3713_caw.analysis.log)
[sample_3998_caw.analysis.log](https://github.com/SciLifeLab/CAW/files/1446289/sample_3998_caw.analysis.log) 

I can try this command you showed me last time, but it would be nice to find out what the problem is.
`singularity exec ~/CAW_analysis/Alena_data/work/singularity/maxulysse-caw-1.2.3.img bash .command.sh`

**Comment by MaxUlysse** [comment]
Hi,
I totally agree with you, it would be good to understand what is the problem.
And I do want to understand why it's failing...

Can you show me a `ls -la` in all these directories?
```
/Z/yafzh/CAW_analysis/subject_1913/work/2d/af5b16a287145484a7d5b11f01b49a
/Z/yafzh/CAW_analysis/subject_3713/work/3d/7076c702d0ea39ba396fa082e9f990
/Z/yafzh/CAW_analysis/subject_3998/work/db/1702ddebdea01e4b56e4f322a2e5d1
```

**Comment by MaxUlysse** [comment]
Can you also show me your `genomes.config` file?
And did you made any change to any other config file?

**Comment by yafeng** [comment]
I have not made any changes to other config file.
`ls -la` has similar output as last time,  it shows a lot vcf files, no vcf.gz file, no header file.

The `.command.err` is either empty or showing this error message which we saw it too last time.
`.command.run.1: line 99: 123595 Terminated              nxf_trace "$pid" .command.trace`

I can come to bioinformatic drop-in time tomorrow if it helps. 


[genomes.config.txt](https://github.com/SciLifeLab/CAW/files/1446383/genomes.config.txt)

**Comment by marcelm** [comment]
> I can come to bioinformatic drop-in time tomorrow if it helps.

That is a really good idea! I will be there.

**Comment by MaxUlysse** [comment]
OK, When is that, I'll try to come to

**Comment by yafeng** [comment]
It is usually 10:30 am at kitchenette gamma 6.
